---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-jenkins
  namespace: {{ template "jenkins.namespace" . }}
spec:
  hosts:
  - "*"
  gateways:
  - {{.Values.jenkins.controller.istioIngressGateways.name | default "jenkins-ingressgateway"}}
  http:
  - match:
    - uri:
        prefix: /jenkins
    route:
    - destination:
        host: {{ template "jenkins.fullname" . }}
        port:
          number: {{.Values.jenkins.controller.servicePort| default 8080}}
      headers:
        request:
          add:
            X-Forwarded-Host: 192.168.59.20
            X-Forwarded-Port: '80'