---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-jenkins
  namespace: {{ template "jenkins.namespace" . }}
spec:
  hosts:
  - "*"
  gateways:
  - {{.Values.controller.istioIngressGateways.name | default "jenkins-ingressgateway"}}
  http:
  - match:
    - uri:
        prefix: /jenkins
    route:
    - destination:
        host: {{ template "jenkins.fullname" . }}
        port:
          number: {{.Values.controller.servicePort}}