jenkins:
  controller:
    jenkinsUriPrefix: /jenkins
    istioIngressGateways:
      name: jenkins-ingressgateway
    podAnnotations:
      proxy.istio.io/config: "{ \"holdApplicationUntilProxyStarts\": true }"
    statefulSetAnnotations:
      proxy.istio.io/config: "{ \"holdApplicationUntilProxyStarts\": true }"
  persistence:
    enabled: false
